### ISSUE TITLE
I would like to have shared cal ability and am willing to fund it, please contact me to discuss

### ISSUE THREAD

**Issue by ekorsi** [mscrivo/OotD#100] opened 2018-07-18 14:22 UTC

**Comment by mscrivo** [comment] 2018-07-21 15:32
Hi @ekorsi, can you be more specific on what you want out of having shared calendar ability?  Are you talking about having multiple people's calendar show up in a single view in OotD?

**Comment by mscrivo** [comment] 2018-07-21 15:32
This is probably a dupe of #86

**Comment by ekorsi** [comment] 2018-07-22 02:52
So I have a shared calendar on exchange server and I want to have that calendar show on prominently on the screen

On Jul 21, 2018, at 11:35 AM, Michael Scrivo <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @ekorsi<https://github.com/ekorsi>, can you be more specific on what you want out of having shared calendar ability? Are you talking about having multiple people's calendar show up in a single view in OotD?

**Comment by mscrivo** [comment] 2018-07-24 00:20
So funding is not the issue here, having access to an exchange server is the issue.  Without that, I can't even begin to implement this or see if it's even possible with the Outlook View Control that Microsoft provides.

**Closed** 2023-05-07 14:07 UTC
Labels: question
