### ISSUE TITLE
Double instance

### ISSUE THREAD

**Issue by Hizaack** [mscrivo/ootd#32] opened 2016-01-06 16:13 UTC
Hello,

I am facing an issue : 

Starting software : default instance
Add instance : the software create 2 instance instead of 1. One instance is the instance created. The second instance is a double of the default instance. It can not be selected. But it can be moved.

See the attached picture. I hope it can help you.

Thank you for your work.

Best regards.
![two_instance](https://cloud.githubusercontent.com/assets/14199145/12147345/b7de3d0c-b498-11e5-8c2c-e0d720b6ab2d.jpg)
![two_instance_2](https://cloud.githubusercontent.com/assets/14199145/12147346/b8265e2a-b498-11e5-87df-7a8fb3c7c5b7.jpg)

**Comment by mscrivo** [comment] 2016-01-12 18:07
Thanks for the bug report.

**Comment by mscrivo** [comment] 2016-02-17 20:11
I haven't found the cause of this yet, it's something to do with the configuration data becoming corrupt.  However, if you open regedit and navigate to 'HKEY_CURRENT_USER\SOFTWARE' and delete 'SMR Computer Services' folder that will reset everything and bug goes away.

**Comment by mscrivo** [comment] 2016-12-07 22:19
Fixed in 3.5

**Closed by mscrivo** 2016-12-07 22:19 UTC
Labels: bug
