### ISSUE TITLE
Error cannot run program

### ISSUE THREAD

**Issue by smsdavis** [mscrivo/OotD#111] opened 2018-09-27 19:13 UTC
Just downloaded and installed the program and it refuses to run.  Unknown Error.  
[2018-09-27.log](https://github.com/mscrivo/OotD/files/2425545/2018-09-27.log)

**Comment by mscrivo** [comment] 2019-05-09 17:21
duplicate of #125

**Closed by mscrivo** 2019-05-09 17:21 UTC
