### ISSUE TITLE
Error when login

### ISSUE THREAD

**Issue by adamlinhub** [mscrivo/OotD#123] opened 2019-04-22 07:58 UTC
[2019-04-22.log](https://github.com/mscrivo/OotD/files/3102659/2019-04-22.log)

![Error on start OotD](https://user-images.githubusercontent.com/49859165/56490528-28bd4f00-64ee-11e9-9922-fea8519486dc.JPG)

When opening the OotD software or trying to install encountered an error.
 OotD version 3.7.5.0

**Comment by mscrivo** [comment] 2019-05-09 02:00
duplicate of #125 Can you please answer the question I posted there?

**Closed by mscrivo** 2019-05-09 02:00 UTC
